sudo: required

services:
  - docker

before_install:
  - docker build -t psreepathi/loginapp .

script:
  - docker run psreepathi/loginapp npm test

after_success:
  # login into docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #push image
  - docker push psreepathi/loginapp